services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: spring-boot-api
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/snippets_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: snippets_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: angular-web
    ports:
      - "4200:4200"
    volumes:
      - ./web:/app
      - /app/node_modules
      - /app/.angular
    depends_on:
      - api

volumes:
  pgdata:

